In [128]:
import pandas as pd
test_data=pd.read_csv("../dataset/processed_testData.csv")
train_data=pd.read_csv("../dataset/processed_trainingData.csv")

In [129]:
train_data = pd.concat([train_data.iloc[:, 0], train_data.iloc[:, -2], train_data.iloc[:, -1]], axis=1)
train_data

,company_name,Processed_model_response,Processed_position_title
0,Google,core responsibility responsible expanding goog...,sale specialist
1,Apple,core responsibility asc highly influential gro...,apple solution consultant
2,Netflix,core responsibility help drive business suppor...,licensing coordinator consumer product
3,Robert Half,core responsibility designing website wirefram...,web designer
4,TrackFive,core responsibility build layout provided psd ...,web developer
...,...,...,...
848,Menards,core responsibility responsibility include wor...,management internship
849,Parker,core responsibility assist general hr function...,human resource internship corporate year round
850,Borgen Project,core responsibility write one article per week...,writer journalist internship
851,Wyndham Destinations,core responsibility answer inbound call excite...,inbound customer service sale remote
852,Aerotek,core responsibility handle incoming call email...,remote inbound customer service representative

In [130]:
import re
# 提取資訊
def extract_information(text):
    patterns = {
        'core_responsibilities': r'core responsibility (.*?) required skill',
        'required_skills': r'required skill (.*?) educational requirement',
        'educational_requirements': r'educational requirement (.*?) experience level',
        'experience_level': r'experience level (.*?) preferred qualification',
        'preferred_qualifications': r'preferred qualification (.*?) compensation benefit',
        'compensation_benefits': r'compensation benefit (.*)'
    }
    
    extracted_info = {}
    
    for key, pattern in patterns.items():
        match = re.search(pattern, text, re.IGNORECASE)
        extracted_info[key] = match.group(1).strip() if match else ''
    
    return pd.Series(extracted_info)

train_data[['core_responsibilities', 'required_skills', 'educational_requirements', 'experience_level', 'preferred_qualifications', 'compensation_benefits']] = train_data['Processed_model_response'].apply(extract_information)

train_data

,company_name,Processed_model_response,Processed_position_title,core_responsibilities,required_skills,educational_requirements,experience_level,preferred_qualifications,compensation_benefits
0,Google,core responsibility responsible expanding goog...,sale specialist,responsible expanding google workspace product...,bachelor degree equivalent experience experien...,bachelor degree equivalent experience,experience managing enterprise saas account sa...,experience building strategic partnership ente...,n
1,Apple,core responsibility asc highly influential gro...,apple solution consultant,asc highly influential growing mind market sha...,passion help people understand apple product e...,n,year preferred,n,n
2,Netflix,core responsibility help drive business suppor...,licensing coordinator consumer product,help drive business supporting licensing manag...,2 year experience preferably outbound licensin...,n,2 year experience preferably outbound licensing,understanding category manufacturing sale cycl...,n
3,Robert Half,core responsibility designing website wirefram...,web designer,designing website wireframes landing page mobi...,2 year experience web design proficiency adobe...,n,2 year,ux ui design experience knowledge brand standa...,n
4,TrackFive,core responsibility build layout provided psd ...,web developer,build layout provided psd file build dynamic w...,2 year experience html cs sas 2 year experienc...,n,2 year,n,free health insurance employee waiting period ...
...,...,...,...,...,...,...,...,...,...
848,Menards,core responsibility responsibility include wor...,management internship,responsibility include working weekend part ti...,specific technical soft skill listed,specific educational requirement listed,specific year experience listed,additional preferred qualification listed beyo...,compensation includes extra pay weekend store ...
849,Parker,core responsibility assist general hr function...,human resource internship corporate year round,assist general hr function like onboarding rec...,pursuing bachelor degree hr business 2 year un...,pursuing bachelor degree hr business field,n,n,n
850,Borgen Project,core responsibility write one article per week...,writer journalist internship,write one article per week research topic assi...,strong research writing skill must able work i...,n,n,experience writing seo friendly content helpfu...,n
851,Wyndham Destinations,core responsibility answer inbound call excite...,inbound customer service sale remote,answer inbound call excited customer intereste...,6 month customer service sale experience abili...,high school diploma ged,6 month customer service sale experience,n,hourly pay plus monthly sale based incentive c...
852,Aerotek,core responsibility handle incoming call email...,remote inbound customer service representative,handle incoming call email person inquiry cust...,customer service phone etiquette communication...,n,n,n,paid time paid training medical dental vision ...

In [131]:
test_data = pd.concat([test_data.iloc[:, 0], test_data.iloc[:, -2], test_data.iloc[:, -1]], axis=1)
test_data = test_data[test_data['Processed_Resume_str'].apply(lambda x: isinstance(x, str))]
test_data

            ID  Category                               Processed_Resume_str
0     16852973        HR  hr administrator marketing associate hr admini...
1     22323967        HR  hr specialist u hr operation summary versatile...
2     33176873        HR  hr director summary 20 year experience recruit...
3     27018550        HR  hr specialist summary dedicated driven dynamic...
4     17812897        HR  hr manager skill highlight hr skill hr departm...
...        ...       ...                                                ...
2479  99416532  AVIATION  rank sgt e 5 non commissioned officer charge b...
2480  24589765  AVIATION  government relation communication organization...
2481  31605080  AVIATION  geek squad agent professional profile support ...
2482  21190805  AVIATION  program director office manager summary highly...
2483  37473139  AVIATION  storekeeper ii professional summary purpose do...

[2483 rows x 3 columns]

In [132]:
# 提取資訊
def extract_resume_information(text):
    patterns = {
        'summary': r'summary (.*?) experience',
        'experience': r'experience (.*?) education',
        'education': r'education (.*?) skills',
        'skills': r'skills (.*)',
    }
    
    extracted_info = {}
    
    for key, pattern in patterns.items():
        match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
        extracted_info[key] = match.group(1).strip() if match else ''
    
    return pd.Series(extracted_info)

test_data[['summary', 'experience', 'education', 'skills']] = test_data['Processed_Resume_str'].apply(extract_resume_information)

# 輸出結果
# test_data=pd.concat([test_data.iloc[:, 0], test_data.iloc[:, 1], test_data.iloc[:, 3],test_data.iloc[:, 4],test_data.iloc[:, 5],test_data.iloc[:, 6]], axis=1)
test_data

,ID,Category,Processed_Resume_str,summary,experience,education,skills
0,16852973,HR,hr administrator marketing associate hr admini...,dedicated customer service manager 15 year,hospitality customer service management respec...,,
1,22323967,HR,hr specialist u hr operation summary versatile...,versatile medium professional background commu...,09 2015 current hr specialist u hr operation c...,,
2,33176873,HR,hr director summary 20 year experience recruit...,20 year,recruiting 15 plus year human resource executi...,,
3,27018550,HR,hr specialist summary dedicated driven dynamic...,dedicated driven dynamic 20 year customer serv...,excellent oral written presentation seasoned c...,,
4,17812897,HR,hr manager skill highlight hr skill hr departm...,,hr manager jan 2015 current company name city ...,,
...,...,...,...,...,...,...,...
2479,99416532,AVIATION,rank sgt e 5 non commissioned officer charge b...,motivated logistics specialist successful mana...,able quickly learn comply military federal reg...,,
2480,24589765,AVIATION,government relation communication organization...,strategically grounded highly,,,
2481,31605080,AVIATION,geek squad agent professional profile support ...,,across multiple discipline including technical...,,
2482,21190805,AVIATION,program director office manager summary highly...,highly personable tech savvy professional 9 pl...,administrative customer service role including...,,
2483,37473139,AVIATION,storekeeper ii professional summary purpose do...,purpose document secure responsible career pos...,contributing goal value organization friendly ...,,

In [133]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import nltk
from nltk.corpus import stopwords

In [134]:
# 下載停用詞列表
# nltk.download('stopwords')

# 加載停用詞列表
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # 去除特殊字符和標點符號
    text = re.sub(r'\W', ' ', text)
    # 轉換小寫
    text = text.lower()
    # 去除多餘的空白字符
    text = re.sub(r'\s+', ' ', text)
    # 去除停用詞
    text = ' '.join(word for word in text.split() if word not in stop_words)
    return text

train_data['label'] = train_data['company_name'] + ' - ' + train_data['Processed_position_title']

train_data['Processed_model_response'] = train_data['Processed_model_response'].apply(preprocess_text)
test_data['Processed_Resume_str'] = test_data['Processed_Resume_str'].apply(preprocess_text)

# train_data['Processed_position_title'] = train_data['Processed_position_title'].apply(preprocess_text)
# test_data['Category'] = test_data['Category'].apply(preprocess_text)

In [2]:
import os
import requests
import zipfile

# 下載模型
def download_glove_model(target_dir):
    
    if not os.path.exists(target_dir):
        os.makedirs(target_dir)
    
    # GloVe 4 模型下載連結
    url = "https://nlp.stanford.edu/data/glove.6B.zip"
    
    # 下載模型文件
    response = requests.get(url)
    
    # 將文件寫入到本地
    with open(os.path.join(target_dir, "glove.6B.zip"), "wb") as f:
        f.write(response.content)
    
    print("Download completed.")

# 解壓縮模型文件
def unzip_model(zip_file, target_dir):
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
        zip_ref.extractall(target_dir)

    print("Extraction completed.")


target_dir = "./glove_model"
download_glove_model(target_dir)
unzip_model(os.path.join(target_dir, "glove.6B.zip"), target_dir)

Download completed.
Extraction completed.

In [ ]:
from gensim.models import KeyedVectors
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# GloVe 詞向量文件
glove_file = "./glove_model/glove.6B.300d.txt"

# 載入 GloVe 模型
model = KeyedVectors.load_word2vec_format(glove_file, binary=False, no_header=True)
model.wv=model
print("Model vocabulary:", len(model.wv.index_to_key))

In [135]:
# 計算 GloVe 向量
def get_glove_vector(text, model):
    words = text.split()
    word_vectors = [model[word] for word in words if word in model.key_to_index]
    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(model.vector_size)

job_vectors = np.array([get_glove_vector(text, model) for text in train_data['Processed_model_response']])
resume_vectors = np.array([get_glove_vector(text, model) for text in test_data['Processed_Resume_str']])

cosine_similarities = cosine_similarity(job_vectors, resume_vectors)

similarity_df = pd.DataFrame(cosine_similarities, index=train_data['company_name'], columns=test_data['ID'])
print(similarity_df)

ID                    16852973  22323967  33176873  27018550  17812897  \
company_name
Google                0.884795  0.887197  0.867525  0.873969  0.891431
Apple                 0.870454  0.886958  0.859189  0.867880  0.888520
Netflix               0.896063  0.920697  0.877879  0.876018  0.903339
Robert Half           0.768078  0.809793  0.752860  0.776578  0.764672
TrackFive             0.903122  0.910189  0.895900  0.901015  0.907449
...                        ...       ...       ...       ...       ...
Menards               0.907337  0.896715  0.912801  0.887636  0.917403
Parker                0.922701  0.908053  0.925197  0.902509  0.936822
Borgen Project        0.871997  0.880320  0.886483  0.879773  0.897771
Wyndham Destinations  0.895084  0.883281  0.877490  0.888896  0.884348
Aerotek               0.919498  0.887376  0.903830  0.923803  0.917829

ID                    11592605  25824789  15375009  11847784  32896934  ...  \
company_name                                                            ...
Google                0.850637  0.864790  0.872045  0.872051  0.884953  ...
Apple                 0.839695  0.844751  0.854689  0.856612  0.843856  ...
Netflix               0.860755  0.871487  0.877406  0.887082  0.882853  ...
Robert Half           0.767729  0.779745  0.752134  0.777670  0.778220  ...
TrackFive             0.883645  0.883955  0.902787  0.906831  0.898690  ...
...                        ...       ...       ...       ...       ...  ...
Menards               0.894715  0.906165  0.915765  0.932886  0.908961  ...
Parker                0.919432  0.928540  0.916629  0.934816  0.931292  ...
Borgen Project        0.883847  0.883352  0.881535  0.907061  0.869686  ...
Wyndham Destinations  0.863257  0.849064  0.879980  0.886865  0.862309  ...
Aerotek               0.886117  0.890075  0.921721  0.917940  0.910381  ...

ID                    28020046  25625173  29534737  17655479  12043694  \
company_name
Google                0.885751  0.861949  0.844579  0.835417  0.842486
Apple                 0.888004  0.840308  0.868039  0.856348  0.823222
Netflix               0.908529  0.877810  0.883708  0.876540  0.855406
Robert Half           0.809335  0.803561  0.792589  0.748844  0.810619
TrackFive             0.903054  0.888287  0.899937  0.893624  0.893674
...                        ...       ...       ...       ...       ...
Menards               0.889584  0.882077  0.894695  0.900093  0.879965
Parker                0.898159  0.897275  0.885902  0.878061  0.886013
Borgen Project        0.886603  0.867296  0.878514  0.862744  0.842765
Wyndham Destinations  0.860881  0.831438  0.869759  0.902576  0.842470
Aerotek               0.899241  0.882229  0.879834  0.893359  0.878586

ID                    99416532  24589765  31605080  21190805  37473139
company_name
Google                0.844326  0.863578  0.841739  0.860498  0.871827
Apple                 0.863455  0.863209  0.820361  0.871570  0.869185
Netflix               0.858166  0.876516  0.847032  0.872317  0.887262
Robert Half           0.744267  0.744527  0.786565  0.770741  0.779261
TrackFive             0.882507  0.868241  0.880537  0.898957  0.905384
...                        ...       ...       ...       ...       ...
Menards               0.904486  0.871909  0.870549  0.900998  0.911029
Parker                0.905941  0.897456  0.872946  0.910185  0.902676
Borgen Project        0.880446  0.852370  0.824921  0.871704  0.869224
Wyndham Destinations  0.896527  0.836718  0.854082  0.895941  0.898770
Aerotek               0.892238  0.855539  0.869102  0.892975  0.908488

[853 rows x 2483 columns]

In [136]:
similarity_df.to_csv("resume_score.csv",index=False)

In [137]:
def find_best_matches(similarity_df, top_n):
    best_matches = {}
    for job_idx in range(similarity_df.shape[0]):
        job = similarity_df.index[job_idx]
        sorted_candidates = similarity_df.iloc[job_idx].sort_values(ascending=False)
        top_matches = sorted_candidates.head(top_n)
        best_matches[job] = list(zip(top_matches.index.tolist(), top_matches.values.tolist()))
    return best_matches


best_matches = find_best_matches(similarity_df, 3)
output_df = pd.DataFrame(best_matches).T
output_df.columns = [f"Top_{i+1}_Resume" for i in range(3)]

In [138]:
output_df['Top_1_Resume_ID'] = output_df['Top_1_Resume'].apply(lambda x: x[0])
output_df['Top_1_Similarity'] = output_df['Top_1_Resume'].apply(lambda x: x[1])

output_df['Top_2_Resume_ID'] = output_df['Top_2_Resume'].apply(lambda x: x[0])
output_df['Top_2_Similarity'] = output_df['Top_2_Resume'].apply(lambda x: x[1])

output_df['Top_3_Resume_ID'] = output_df['Top_3_Resume'].apply(lambda x: x[0])
output_df['Top_3_Similarity'] = output_df['Top_3_Resume'].apply(lambda x: x[1])

output_df.drop(columns=['Top_1_Resume', 'Top_2_Resume', 'Top_3_Resume'], inplace=True)

output_df.insert(0, 'Position', train_data['Processed_position_title'].values)

id_to_category = dict(zip(test_data['ID'], test_data['Category']))

output_df.insert(2, 'Top_1_Category', output_df['Top_1_Resume_ID'].map(id_to_category))
output_df.insert(4, 'Top_2_Category', output_df['Top_2_Resume_ID'].map(id_to_category))
output_df.insert(6, 'Top_3_Category', output_df['Top_3_Resume_ID'].map(id_to_category))

In [139]:
output_df

,Position,Top_1_Resume_ID,Top_1_Category,Top_1_Similarity,Top_2_Category,Top_2_Resume_ID,Top_3_Category,Top_2_Similarity,Top_3_Resume_ID,Top_3_Similarity
Google,sale specialist,17189156,BANKING,0.929100,CONSULTANT,78016758,BPO,0.924444,13964744,0.923738
Apple,apple solution consultant,13386301,APPAREL,0.943484,CHEF,23591247,BANKING,0.935287,17189156,0.935162
Netflix,licensing coordinator consumer product,26278597,BUSINESS-DEVELOPMENT,0.944829,BUSINESS-DEVELOPMENT,13080868,SALES,0.941725,28867567,0.940289
Robert Half,web designer,33141415,CONSTRUCTION,0.922218,INFORMATION-TECHNOLOGY,83816738,AVIATION,0.906376,12144825,0.904094
TrackFive,web developer,28126340,INFORMATION-TECHNOLOGY,0.940908,CONSULTANT,20314980,PUBLIC-RELATIONS,0.940627,26127853,0.940331
...,...,...,...,...,...,...,...,...,...,...
Menards,management internship,56151548,APPAREL,0.936368,TEACHER,27531694,FITNESS,0.936272,28669770,0.936144
Parker,human resource internship corporate year round,20925036,HR,0.945559,HR,59962788,HR,0.944927,16877897,0.944502
Borgen Project,writer journalist internship,66683238,TEACHER,0.931108,ADVOCATE,24588864,HR,0.928085,24508725,0.927697
Wyndham Destinations,inbound customer service sale remote,34146825,ARTS,0.943129,ARTS,20148147,DESIGNER,0.941935,29865476,0.941302
Aerotek,remote inbound customer service representative,64471954,HEALTHCARE,0.957275,ADVOCATE,49486820,ADVOCATE,0.953289,13342150,0.952366

In [141]:
output_df.to_csv('best_matches.csv',index_label="Company")